/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 house_interior_empty_free_3d_model.glb 
Author: Scalzotto Design (https://sketchfab.com/scalzotto_design)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/house-interior-empty-free-3d-model-25bc35ea1ff14d75899b3cbdee836332
Title: House Interior Empty Free 3D model
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/house_interior_empty_free_3d_model.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.009}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.diffuse_Aqua} /> 
        <mesh geometry={nodes.Object_2.geometry} material={materials.Material} material-color={props.wallColor} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.diffuse_Black} />
        <mesh geometry={nodes.Object_2.geometry} material={materials.Material} material-color={props.wallColor} />

        <mesh geometry={nodes.Object_4.geometry} material={materials.diffuse_Black} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.diffuse_Black} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.diffuse_Black} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.diffuse_Black} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.diffuse_Blue} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.diffuse_Blue} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.diffuse_Blue} />
      </group>
    </group>
  )
}

useGLTF.preload('/house_interior_empty_free_3d_model.glb')
