/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 sofa.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/sofa.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.018, -0.001, -0.046]} rotation={[-Math.PI / 2, 0, 0.306]} scale={0.001}>
        <group position={[38.138, 51.676, 6.321]} scale={0.4}>
          <mesh geometry={nodes.Bottom_piece.geometry} material={materials['Material #26 1']} position={[-281.033, -1.263, 263.752]} />
          <mesh geometry={nodes.Wood_part.geometry} material={materials['Wood 2']} position={[-281.033, -1.263, 263.752]} />
          <mesh geometry={nodes.Gold_piece.geometry} material={materials['Material #26']} position={[-281.033, -1.263, 263.752]} />
        </group>
        <mesh geometry={nodes.Plywood.geometry} material={materials['Wood 3']} position={[-70.065, 51.91, 147.816]} scale={0.4} />
        <mesh geometry={nodes.Seat.geometry} material={materials['Red velvet']} position={[-9.537, 51.274, 214.349]} scale={0.4} />
        <mesh geometry={nodes.Pillow.geometry} material={materials['Fabric 2']} position={[62.434, 102.691, 268.471]} scale={0.275} />
      </group>
      <mesh geometry={nodes.Green_plant_monstera.geometry} material={materials.Amulet} position={[0.077, 0.214, 0.18]} rotation={[-Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes.Coffee_Table.geometry} material={materials['Eagle Eye']} position={[0.072, 0.212, 0.164]} rotation={[-Math.PI / 2, 0, 0.306]} scale={0} />
    </group>
  )
}

useGLTF.preload('/sofa.gltf')
